#pragma once

#define TAPPING_TOGGLE 2
// TT set to two taps

#define TAPPING_TERM 165

#define VIAL_ENCODER_DEFAULT { KC_VOLD, KC_VOLU, RGB_MODE_REVERSE, RGB_MODE_FORWARD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS }
#define VIA_CUSTOM_LIGHTING_ENABLE
#define VIA_QMK_RGBLIGHT_ENABLE